name: 'Visual E2E testing with Testube'
description: 'Run e2e tests'
inputs:
  suite-number:
    description: 'The number of the test suite to run.'
    required: true
  api-key:
    description: 'The API key to use for authentication.'
    required: true
  secret:
    description: 'The secret to use for authentication.'
    required: true
outputs:
  test-results:
    description: 'The results of the test execution.'
runs:
  using: 'node16'
  main: 'index.mjs'